repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=3500']


-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
      args: ["--line-length", "110"]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      args: # arguments to configure flake8
        # making isort line length compatible with black
        - "--max-line-length=110"

        # these are errors that will be ignored by flake8
        # check out their meaning here
        # https://flake8.pycqa.org/en/latest/user/error-codes.html
        - "--ignore=E203,E266,E501,W503,E402,E401"
        - "--per-file-ignores=*/__init__.py: F401"

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.6.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        additional_dependencies: [
            msgspec==0.19.0,
            types-pkg_resources==0.1.3,
        ]


-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args:
          - --add-import
          - from __future__ import annotations


-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck


-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.4
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, "sqlite"]
